# Generated by Django 5.0.4 on 2026-01-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='include_in_weekly_summary',
            field=models.BooleanField(default=False, verbose_name='Include in Weekly Summary'),
        ),
    ]
